### ISSUE TITLE
Integrate with invoke

### ISSUE THREAD

**Issue by thedrow** [illBeRoy/taskipy#13]
[Invoke ](http://www.pyinvoke.org/) is a task execution tool & library commonly used to manage different tasks when developing a project.

If we could integrate this project with invoke to automatically trigger invoke tasks that would be great.

**Comment by illBeRoy** [comment]
Hello!

First of all thanks for taking the time to open an issue :)

To my understanding, `invoke` has its own cli that runs its tasks. Wouldn't creating a task that uses it be sufficient? e.g.:

```toml
[tool.taskipy.tasks]
build = "invoke build"
```

Or did you have another idea in mind?

**Comment by thedrow** [comment]
If a `tasks.py` file is present we can automatically call it using invoke e.g.
```
poetry run task build
```

**Comment by illBeRoy** [comment]
Sounds like an interesting idea :)

The request is a bit out of the domain of Taskipy, but perhaps it can be implemented in a form of an extension.

I'll draft something out and update you once it's up

**Comment by illBeRoy** [comment]
Hi,

I know that it's been some time since you've opened this issue, but this is now possible using the [custom runners](https://github.com/illBeRoy/taskipy/blob/master/docs/ADVANCED_FEATURES.md#custom-runners) feature (with `invoke` being the runner).

I'm closing the issue for now but feel free to re-open it if you have any further questions :)
