### ISSUE TITLE
Run pre/post hooks on built-in Poetry commands

### ISSUE THREAD

**Issue by filips123** [illBeRoy/taskipy#29]
Is it possible to add support for adding pre/post hooks on built-in Poetry commands, for example `poetry build` or `poetry publish`? This would be useful when you want to automatically add some, maybe auto-generated, files to build and clean them after they are packaged.

Similar thing can also be done by adding custom `build` task that calls `poetry build` and executing `poetry run task build`, but I think calling original `poetry build` directly would be better experience.

npm and other package managers for other languages also [provide](https://docs.npmjs.com/cli/v6/using-npm/scripts#life-cycle-operation-order) similar feature.

**Comment by eugenetriguba** [comment]
@filips123 Obviously, this is up to @illBeRoy to decide but personally, it feels like this would add a lot of complexity to the project and future maintenance for marginal gains (`poetry run task build` or if in the virtualenv, `task build` vs `poetry build` ). It also seems like it would be confusing if one cli is altering what happens when another cli runs a command. Furthermore, it is actually shorter if you're in the virtualenv to use the task command so I'm not sure if it is clear-cut that what you are proposing is a better experience. Lastly, I don't immediately see any obvious way to implement this. Is taskipy supposed to somehow listen to every terminal command and run a pre-hook and post-hook when a specific one runs? Where would you even specify these, still in the `pyproject.toml` as a task? But it doesn't work like the other tasks? It seems confusing and not really a fit for this project.

I'm also not sure if the `npm` example is completely valid here. I get what you're saying, but `npm` has pre and post commands on its own cli commands, not other cli tools. Right now, taskipy is just a cli tool. Furthermore, [it does have support for pre and post hooks on its own commands](https://github.com/illBeRoy/taskipy#pre-task-hook), like npm does. The `poetry run` part just allows you to run it in the virtualenv so you can access the tools you've installed in that environment. The feature you're asking for seems like more of a feature request for poetry itself so I feel this issue is better directed to them.

I would favor the simpler approach of using a `task build` command.

**Comment by illBeRoy** [comment]
Hey @filips123 !

First of all, thanks for reaching out. It's always fun to see feedbacks and suggestions from users.

As per your suggestion, I tend to agree with @eugenetriguba here. While it works really nicely with poetry, taskipy is actually not part of the poetry package manager. Therefore, this behavior might confuse people who choose to go with taskipy without using poetry. In addition, having taskipy run pre and post scripts for the `poetry build` command would mean that taskipy will actually have to "take over" poetry and replace it with a proxy of sorts, as they currently do not have a built in plugin system and we would have no way of knowing when the user is running `poetry build` otherwise.

So in that case, I think that Eugene's suggestion is the best approach for you here: simply create a task called `build` and put `poetry build` inside. That way you get to enjoy both worlds. As a matter of fact, that is exactly what we do with our **own** [publish task](https://github.com/illBeRoy/taskipy/blob/master/pyproject.toml#L44)!

Hopefully, the answer was sufficient. If you have any other questions, please let me know :)
