### ISSUE TITLE
Allow for task documentation / explanatory text 

### ISSUE THREAD

**Issue by vergenzt** [illBeRoy/taskipy#34]
E.g. "use this task for ..."

I'm trying to set up a repo to be easy to use by new contributors, so it'd be nice to have some explanatory text output alongside the task names/definitions output by `task --list`.

**Comment by eugenetriguba** [comment]
I agree. I think this also would be nice to have. Only showing the task name and it's corresponding command doesn't seem super friendly. What were you thinking in particular for this?

Are you saying in addition to the task name and command, there should be help output with the list command? As in show the task name, task command, and task description?

Or were you saying when the list command is run, the "help" text should replace the command text? As in show only the task name and its description next to it.

A concern with the former is space in the terminal. It could cause a lot of wrapping if all are side by side. A concern with the latter may be what do we do when there is no help text then? Do we default back to just showing the command in place of the help text?

There’s also a question of where/how we would add this help text into the configuration. My initial thought was something along the lines of: 

[tool.taskipy.tasks]
test = { command = "poetry run pytest tests/", help = "Runs the unit tests" }

Let me know your thoughts. I could do the work for this if this is desired but would need @illBeRoy to let us know if it is.

**Comment by illBeRoy** [comment]
I love this idea :) the addition of help messages can really improve visibility and explicitness of commands.

As for @eugenetriguba notes:
1. I agree with the format idea and think it would be simple to implement and use, but maybe we should use `cmd` instead of `command`? It's shorter and less prone to spelling mistakes.

2. We can handle wrapping of help text same way that argparse does, e.g.:
```sh
$ task --list
test    this is a long description and blah blah loren ipsum and
          wrapping just keeps indentation along lines
lint
```

3. Just a though here, how about we propose (in the docs) that people use the following notation:
```toml
[tool.taskipy.tasks]
test = "poetry run pytest tests/"
lint = "poetry run pylint"

[tool.taskipy.tasks.run]
cmd = "python cli.py"
help = "runs the cli"
```

If we agree upon the details, I'll open a PR and assign you as reviewers. Been long since I contributed code to this project ;)

**Comment by eugenetriguba** [comment]
1. I think `cmd` works just as well, short and clear.

2. This looks good to me. It seems like you're leaning towards the third option then? Show the help text if it is there and show just the task name if it is not? I believe this is the route invoke uses for listing its commands (http://docs.pyinvoke.org/en/0.12.1/getting_started.html#listing-tasks).

3. I had to look up to the toml spec to double-check that

```
[tool.taskipy.tasks.run]
cmd = "python cli.py"
help = "runs the cli"
```

and

```
[tool.taskipy.tasks]
run = { cmd = "python cli.py", help = "runs the cli" }
```

are equivalent since I couldn't remember if supporting both would require any extra work. I don't believe so. In particular, the spec says "Inline tables are intended to appear on a single line. A terminating comma (also called trailing comma) is not permitted after the last key/value pair in an inline table. No newlines are allowed between the curly braces unless they are valid within a value. Even so, it is strongly discouraged to break an inline table onto multiples lines. If you find yourself gripped with this desire, it means you should be using standard tables." (https://toml.io/en/v1.0.0#inline-table)

My only reservation with showcasing only the first notation in the docs is that I think some people may find it offputting with how verbose it is if they are not aware of the second option and its equivalence with the first. While it looks like the first option is the preferred way to do it if someone is going to have multiline help text, I feel as though that is more of an exceptional than a typical case. (Just like some have found it offputting that you have to run "poetry run task whatever" instead of just "task whatever" if they're not aware of what "poetry run" is actually doing and that you can get around this by going into the virtualenv)

For instance, with poetry you can do:

```
[tool.poetry.dependencies.some_module]
develop = true
path = "src/some_module"
```

and

```
[tool.poetry.dependencies]
some_module = { path = "src/some_module", develop = true }
```

However, It's quite infrequent I see the first one because of how verbose it can get if you're doing that for every dependency. That's more of a documentation detail than an implementation detail and at the end of the day, up to you. I just wanted to raise that concern as something to consider.

**Comment by illBeRoy** [comment]
Got it, valid points :)
Will get to it and open PR soon

**Comment by illBeRoy** [comment]
hi @vergenzt ! we added this as a feature in `taskipy==1.8.0`! You can read about this [here](https://github.com/illBeRoy/taskipy#adding-tasks)!

**Comment by vergenzt** [comment]
Yay! Glad y'all were able to get this added. :) Unfortunately I ended up switching to using https://www.pyinvoke.org/ for the project I'm working on at the moment, but I'll give this library another look in the future!
