### ISSUE TITLE
Use single underscore for non-public methods and instance variables

### ISSUE THREAD

**Issue by eugenetriguba** [illBeRoy/taskipy#41]
According to PEP8 (https://www.python.org/dev/peps/pep-0008/#method-names-and-instance-variables):

> Use one leading underscore only for non-public methods and instance variables. 

> To avoid name clashes with subclasses, use two leading underscores to invoke Python's name mangling rules.

The project currently uses the double underscore `__` prefix to denote private instance variables and methods. I would propose altering that to use a single `_` underscore.

The purpose is twofold.

1. It is the standard convention and conforms to the standard python style. There isn't any sub-classing so there isn't a real need for the name mangling.
2. If we wanted to unit test these methods, it is much cleaner to use `_pyproject` than `_TaskRunner__pyproject` inside of those unit tests.

I recognize that I likely may have started or at the least influenced the double underscore convention here via #15 :smile:

**Comment by Granitosaurus** [comment]
+1; I'm generally not a fan of double underscores and in general think that even single underscore should be used sparingly.

**Comment by illBeRoy** [comment]
Hi! Thanks for the suggestion!

IMO double **underscore is preferable**, because it has actual practical use over single underscore. Double underscore gives you encapsulation - and in an OOI world this is **always** a good idea, regardless of whether or not you intend for your class to be subclassed. I know that Guido is more in favor of the "open kimono" approach (what an outdated and inappropriate term!) - but in this case (single vs double underscore) I think that safety beats comfort so there's a solid case for breaking the convention here.

As for unit tests, they are not a concern imo. I am a huge TDD advocate, so IMO all tests should be black box and we should never test private methods. If you agree with me about that, then name mangling is not a problem - to the contrary, we would much rather not know anything about private methods and fields during tests.

Finally, I agree with your that a single underscore is the standard. But double underscore is not that obscure as to confuse other python devs regarding what you mean. It has leading underscore\s? It's a private method, no doubt about it. And anyways, as per PEP8:

> In the event of any conflicts, such project-specific guides take precedence for that project.

And in that case, as long as we consistently use double underscore across the codebase, we're good to go :)

**Comment by eugenetriguba** [comment]
@illBeRoy I'm not bullish on it, just bringing it up as a possible suggestion. I appreciate you taking the time to give your thoughts!

I don't think I would agree that using double underscores gives you any more encapsulation than using a single underscore. I agree encapsulation is important, no disagreement there, just that using the double underscores isn't any different. 
- It doesn't prevent access for anyone who wants to use internals.
- It mangles the name in a very predictable `_classname__attr` form.
- It's designed to help prevent issues with subclassing. 

Really, it just makes it more verbose to access those internals for someone who wants to.

```python
>>> class A:
...   def __init__(self):
...     self.__test = 'a'
...     self._test = 'a'
... 
>>> dir(A())
['_A__test', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_test']
```

Note the `_A__test` and `_test` are both shown and available.

Python doesn't really have firm encapsulation in that kind of way. You convey which attributes or methods are internal and trust that your client knows what they're doing if they use them because those are internals that can change at anytime. 

If you accept the premise that using double underscores isn't any different encapsulation-wise, it felt like it made sense to just keep things simpler and follow the standard convention.

Feel free to close if you feel strongly otherwise :slightly_smiling_face:

**Comment by illBeRoy** [comment]
My intention was not to stop people from tampering with our classes on purposes - if they want to mess with the internals then by all means go ahead (and since taskipy is OSS they can literally tamper with the entire codebase)

Instead, I want to make sure (as much as possible) that people will not break things by mistake. I want to keep **them** safe. Name mangling, while not giving you complete encapsulation, helps you prevent accidental overloading by namespacing method names, therefore making them less prone to collisions.

And I know that PEP says that you should use it if you design your class for inheritance, by IMO **every** class should be inheritable, as inheritance is a 100% legit way to extend pieces of software.

Since the mental overload of just using two `_` instead of one is worth the benefit IMO, I really do feel that we should aim to use double underscore as much as possible - as long as we keep this standard consistent across our codebase.

I hope that I managed to get my point across. Even if you don't agree with me on this one, I really don't want to reject things "just because I said so", and always aim to provide reasonable explanations :)

BTW,

Even languages that offer "true" encapsulation usually give you the option to bypass their own rules, whether its by Java [Reflections](http://tutorials.jenkov.com/java-reflection/private-fields-and-methods.html) or CPP pointer magic, etc.

**Comment by eugenetriguba** [comment]
No worries, I appreciate you giving your thoughts 🙂 it’s a minor thing, just figured I’d bring it up as a consideration. I’ll close this one out
